{% set name = "tika" %}
{% set version = "1.22" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "a090a0968e7224e12df6d37e2fe4e809397bd87be54778f44621906f3afa1c8a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  entry_points:
    - tika-python = tika.tika:main
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python

  run:
    - python
    - setuptools
    - requests

test:
  imports:
    - tika
    - tika.tests

  commands:
    - tika-python --help

about:
  home: http://github.com/chrismattmann/tika-python
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Apache Tika Python library'
  doc_url: https://github.com/chrismattmann/tika-python
  dev_url: https://github.com/chrismattmann/tika-python

extra:
  recipe-maintainers:
    - pmlandwehr
    - chrismattmann
